#' Example National Address Database addresses
#'
#' @description
#' A small baked example fixture containing Hamilton County, Ohio National
#' Address Database (NAD version `22L`) rows needed by package examples and
#' tests. See `?nad` for more information about the National Address Database.
#'
#' The fixture was derived once from the Hamilton County NAD source data and is
#' not intended to be regenerated by package users. Use `nad()` when you need
#' complete county data.
#'
#' @param match_prepared logical; return the example data preprocessed with
#'   `addr_match_prepare()`?
#' @returns If `match_prepared = FALSE`, a tibble with 5,000 rows and 7
#'   columns. If `match_prepared = TRUE`, an `addr_match_index`.
#' @export
#' @examples
#' nad_example_data()
#' nad_example_data(match_prepared = TRUE)
nad_example_data <- function(match_prepared = FALSE) {
  stopifnot(
    "match_prepared must be TRUE or FALSE" = is.logical(match_prepared) &&
      length(match_prepared) == 1L &&
      !is.na(match_prepared)
  )

  if (match_prepared) {
    return(
      readRDS(
        system.file(
          "extdata",
          "nad_39061_mp.rds",
          package = "addr",
          mustWork = TRUE
        )
      )
    )
  }

  readRDS(
    system.file(
      "extdata",
      "nad_39061.rds",
      package = "addr",
      mustWork = TRUE
    )
  )
}

#' Example addresses
#'
#' `voter_addresses()` returns a small baked example character vector derived
#' from real-world addresses originally downloaded from the Hamilton County,
#' Ohio voter registration database on 2024-09-12. The original export URL was
#' <https://votehamiltoncountyohio.gov/download.php?file=VoterListExport-20240912-no.csv>,
#' although that URL is not expected to remain available. Fields named
#' `AddressPreDirectional`, `AddressNumber`, `AddressStreet`, `AddressSuffix`,
#' `CityName`, `"OH"`, and `AddressZip` were pasted together before reducing the
#' source to 2,000 unique registered-voter address examples. The fixture is not
#' intended to be regenerated by package users.
#' @returns a character vector
#' @export
#' @examples
#' voter_addresses() |>
#'   head()
voter_addresses <- function() {
  readRDS(
    system.file(
      "extdata",
      "voter_addresses.rds",
      package = "addr",
      mustWork = TRUE
    )
  )
}

#' Example line-one addresses
#'
#' The Cincinnati Eviction Hotspots data was downloaded from
#' [Eviction Labs](https://evictionlab.org/uploads/cincinnati_hotspots_media_report.csv)
#' and contains characteristics of the top 100 buildings that are responsible for about 25% of
#' all eviction filings in Cincinnati (from their "current through 8-31-2024" release).
#' @details https://evictionlab.org/eviction-tracking/cincinnati-oh/
#' @returns a tibble with 100 rows and 9 columns
#' @export
#' @examples
#' elh_data()
elh_data <- function() {
  readRDS(
    system.file(
      "extdata",
      "elh_data.rds",
      package = "addr",
      mustWork = TRUE
    )
  )
}
