# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_addr_wrappers", use_symbols = TRUE, package_name = "addr")

#' @usage NULL
#' @useDynLib addr, .registration = TRUE
NULL

#' run usaddress::parse on a vector of strings
usaddress_tag <- function(x) .Call(wrap__usaddress_tag, x)


# nolint end
